version: "3.3"

services:

  example2_blog:

    image: ghost:4.3.3-alpine

    # map host port 9199 (external) to Ghost's default internal port 2368
    ports:
      - 9199:2368

    environment:
      # the url of your other blog. 
      url: https://example2.com                                           

    labels:
     # tells Traefik to detect this docker container
     - traefik.enable=true

     # tells Traefik to look and match the host name chuenl.com
     - traefik.http.routers.example2_blog.rule=Host(`example2.com`)

     # tells Traefik to use the 'websecure' http router entry point.
     - traefik.http.routers.example2_blog.entrypoints=websecure

     # tells Traefik what certificate resolver to use - 'myresolver'
     - traefik.http.routers.example2_blog.tls.certresolver=myresolver

    volumes:
      # maps Ghost's data directory to the hosts directory.
      - /home/deploy/ghost_data/example2_blog/data:/var/lib/ghost/content

    networks:
     - web

networks:
  web:
    external: true
